# @package _global_

name: adaclip_high_contrast

defaults:
  - /pipeline/anomaly/adaclip@pipeline: adaclip_high_contrast
  - /data@data: lentils
  - _self_

data:
  # Override splits for this example
  train_ids: [0, 2]
  val_ids: [2, 4]
  test_ids: [1, 3, 5]
  batch_size: 1

output_dir: outputs\adaclip_high_contrast

metric_nodes:
- detection_metrics

loss_nodes: []

