# @package _global_

name: adaclip_baseline

defaults:
  - /pipeline@pipeline: adaclip_baseline
  - /data@data: lentils
  - _self_

data:
  # Override splits for this example
  train_ids: [0, 2]
  val_ids: []
  test_ids: [1, 3, 5]
  batch_size: 3

output_dir: outputs\adaclip_baseline

# AdaCLIP & example-specific parameters
# adaclip:
#   model_name: ViT-L-14-336
#   weight_name: pretrained_all
#   prompt: "normal: lentils, anomaly: stones"
#   gaussian_sigma: 4.0
#   target_class_id: 3
#   use_half_precision: false  # Set to false to match old non-optimized version
#   enable_warmup: false      # Set to false to match old non-optimized version

# decider:
#   quantile: 0.995

# viz:
#   up_to: 3

# metric_nodes:
# - detection_metrics

# loss_nodes: []

# # Baseline false-RGB wavelengths: R, G, B
# baseline:
#   target_wavelengths: [650.0, 550.0, 450.0]

