# @package _global_


defaults:
  - /pipeline/anomaly/rx@pipeline: channel_selector
  - /data@data: lentils
  - /training@training: default
  - _self_

name: base_trainrun
output_dir: ./outputs/${name}

training:
  trainer:
    default_root_dir: ${output_dir}
    
hydra:
  run:
    dir: ${output_dir}
  output_subdir: .hydra
