# @package _global_


defaults:
  - /pipeline@pipeline: rx_statistical
  - /data@data: lentils
  - _self_

name: base_trainrun
output_dir: ./outputs/${name}

hydra:
  run:
    dir: ${output_dir}
  output_subdir: .hydra
